services:
  api_input:
    env_file:
      - path: ./.env
        required: true
    image: mathcale/goexpert-lab-otel-challenge-input
    build:
      context: .
      dockerfile: Dockerfile.input
    ports:
      - "${INPUT_SERVICE_WEB_SERVER_PORT}:${INPUT_SERVICE_WEB_SERVER_PORT}"

  api_orchestrator:
    env_file:
      - path: ./.env
        required: true
    image: mathcale/goexpert-lab-otel-challenge-orchestrator
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "${ORCHESTRATOR_SERVICE_WEB_SERVER_PORT}:${ORCHESTRATOR_SERVICE_WEB_SERVER_PORT}"

  collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
