version: "3.8"

services:
  api:
    env_file:
      - path: ./.env
        required: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
